### ISSUE TITLE
Why did you fork?

### ISSUE THREAD

**Issue by rapgro** [mhogomchungu/ecryptfs-simple#1]
Is http://xyne.archlinux.ca/projects/ecryptfs-simple/src/ dead? I see latest release there is from 2016-11-13.

**Comment by mhogomchungu** [comment]
Upstream is very much alive,i created this fork just to put the code on github because upstream isnt here.

Its easier to keep track of changes,accept bug reports,pull requests and have discussions when projects are hosted "properly".

Functionality wise,this forks adds support for unlocking volumes in read only mode but i think upstream will eventually add it.

**Comment by mhogomchungu** [comment]
Closing this one,look at this[1] arch linux thread and you will see this fork is my base when discussing code changes and improvements with upstream.

[2] https://bbs.archlinux.org/viewtopic.php?id=142328

**Comment by mhogomchungu** [comment]
If you do not know, i have a project called "SiriKali"[1] and it uses "ecryptfs-simple" backed to create and unlock ecryptfs volumes.

The primary reason why i created this fork was to easily modify it to better integrate it with SiriKali and i discussed all my changes and improvements with upstream in the arch linux forum page i linked above. This fork and upstream will always be in sync and loose its purpose once upstream picks up all my changes with the relevant change being an ability to unlock volumes in read only mode.

[1] https://mhogomchungu.github.io/sirikali/

**Comment by mhogomchungu** [comment]
just checked and upstream now supports unlocking of volumes in read only mode the way my fork does it and this makes upstream and this fork identical and any one of the two can be used.

Will keep this fork online until upstream "show up" here at github.

**Comment by rapgro** [comment]
Thanks for the good work. I'll keep my review request for a Fedora package with the link to GitHub.
